name: library

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get install -y libegl-dev libgl-dev
      - uses: erlangsters/setup-erlang@v1
        with:
          erlang-version: 28
          install-rebar3: true
      - run: rebar3 compile

  # On macOS and Windows, the EGL dependency will need the location of ANGLE
  # libraries and headers (which we specify via environment variables).
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlangsters/setup-erlang@v1
        with:
          erlang-version: 28
          install-rebar3: true
      - id: angle
        uses: erlangsters/setup-angle@v1
      - run: |
          export ANGLE_INCLUDE_DIR="${{ steps.angle.outputs.angle-location }}/include"
          export ANGLE_LIB_DIR="${{ steps.angle.outputs.angle-location }}/lib"
          rebar3 compile

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlangsters/setup-erlang@v1
        with:
          erlang-version: 28
          install-rebar3: true
      - id: angle
        uses: erlangsters/setup-angle@v1
      - run: |
          $angleLocation = "${{ steps.angle.outputs.angle-location }}"
          $env:ANGLE_INCLUDE_DIR = "$angleLocation\include"
          $env:ANGLE_LIB_DIR = "$angleLocation\lib"
          rebar3 compile
        shell: pwsh
